import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Navbar from "./components/Navbar/Navbar";
import { cn } from "@/lib/utils";
import SiteHeader from "./components/SiteHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AmeboNaija",
description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${cn("min-h-screen bg-bacground font-sans antialiased")} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="relative flex min-h-dvh flex-col- bg-background">
          <SiteHeader />
          {/* <Navbar /> */}
          {/* <main className="flex-1"> */}
            {children}
          {/* </main> */}
        </div>
      </body>
    </html>
  );
}
